
#ifndef ERRORCODES_H
#define ERRORCODES_H

#define ERR01 "INVALID-TILE-POSITION"

#define ERR02 "INVALID-SQUARE-INDEX"

#define ERR03 "NO-ROOM-FOR-TILES"

#define ERR04 "NO-ROOM-FOR-TILES"

#define ERR05 "NO-MORE-TILES"

#define ERR06 "LETTER-NOT-IN-RACK"

#define ERR07 "INVALID-DIRECTION"

#endif
